-- MOVA Migration 005 — Vehicle Requests & Trips
-- Depends on: customers (003), users (004), vehicles (004)

CREATE TABLE IF NOT EXISTS `mova_vehicle_requests` (
    `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    `customer_id` BIGINT UNSIGNED NOT NULL,
    `request_number` VARCHAR(30) NOT NULL COMMENT 'REQ-YYYY-NNNN',
    `requested_by` BIGINT UNSIGNED NOT NULL,
    `department` VARCHAR(80) NULL,
    `destination` VARCHAR(150) NOT NULL,
    `purpose` TEXT NOT NULL,
    `departure_date` DATE NOT NULL,
    `return_date` DATE NOT NULL,
    `passenger_count` INT NOT NULL DEFAULT 1,
    `vehicle_preference` VARCHAR(50) NULL,
    `assigned_vehicle_id` BIGINT UNSIGNED NULL,
    `assigned_driver_id` BIGINT UNSIGNED NULL,
    `status` ENUM('pending', 'approved_l1', 'approved', 'rejected', 'cancelled') NOT NULL DEFAULT 'pending',
    `approved_by_l1` BIGINT UNSIGNED NULL,
    `approved_at_l1` TIMESTAMP NULL,
    `approved_by_l2` BIGINT UNSIGNED NULL,
    `approved_at_l2` TIMESTAMP NULL,
    `rejected_by` BIGINT UNSIGNED NULL,
    `rejection_reason` TEXT NULL,
    `notes` TEXT NULL,
    `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (`id`),
    UNIQUE KEY `uk_request_number` (`request_number`),
    KEY `idx_customer_id` (`customer_id`),
    KEY `idx_requested_by` (`requested_by`),
    KEY `idx_status` (`status`),
    KEY `idx_assigned_vehicle` (`assigned_vehicle_id`),
    KEY `idx_assigned_driver` (`assigned_driver_id`),
    CONSTRAINT `fk_vr_customer` FOREIGN KEY (`customer_id`) REFERENCES `mova_customers` (`id`) ON DELETE CASCADE,
    CONSTRAINT `fk_vr_requested_by` FOREIGN KEY (`requested_by`) REFERENCES `mova_users` (`id`) ON DELETE RESTRICT,
    CONSTRAINT `fk_vr_vehicle` FOREIGN KEY (`assigned_vehicle_id`) REFERENCES `mova_vehicles` (`id`) ON DELETE SET NULL,
    CONSTRAINT `fk_vr_driver` FOREIGN KEY (`assigned_driver_id`) REFERENCES `mova_users` (`id`) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `mova_trips` (
    `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    `customer_id` BIGINT UNSIGNED NOT NULL,
    `vehicle_request_id` BIGINT UNSIGNED NULL,
    `vehicle_id` BIGINT UNSIGNED NOT NULL,
    `driver_id` BIGINT UNSIGNED NOT NULL,
    `trip_number` VARCHAR(30) NOT NULL COMMENT 'TRP-YYYY-NNNN',
    `origin` VARCHAR(100) NOT NULL,
    `destination` VARCHAR(100) NOT NULL,
    `trip_date` DATE NOT NULL,
    `departure_time` TIME NULL,
    `return_time` TIME NULL,
    `km_start` INT NULL,
    `km_end` INT NULL,
    `distance_km` INT NULL,
    `purpose_type` VARCHAR(50) NOT NULL COMMENT 'dinas, material, karyawan, klien, lainnya',
    `notes` TEXT NULL,
    `status` ENUM('draft', 'in_progress', 'completed', 'cancelled') NOT NULL DEFAULT 'draft',
    `input_by` BIGINT UNSIGNED NOT NULL,
    `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (`id`),
    UNIQUE KEY `uk_trip_number` (`trip_number`),
    KEY `idx_customer_id` (`customer_id`),
    KEY `idx_vehicle_id` (`vehicle_id`),
    KEY `idx_driver_id` (`driver_id`),
    KEY `idx_status` (`status`),
    KEY `idx_trip_date` (`trip_date`),
    CONSTRAINT `fk_trips_customer` FOREIGN KEY (`customer_id`) REFERENCES `mova_customers` (`id`) ON DELETE CASCADE,
    CONSTRAINT `fk_trips_request` FOREIGN KEY (`vehicle_request_id`) REFERENCES `mova_vehicle_requests` (`id`) ON DELETE SET NULL,
    CONSTRAINT `fk_trips_vehicle` FOREIGN KEY (`vehicle_id`) REFERENCES `mova_vehicles` (`id`) ON DELETE RESTRICT,
    CONSTRAINT `fk_trips_driver` FOREIGN KEY (`driver_id`) REFERENCES `mova_users` (`id`) ON DELETE RESTRICT,
    CONSTRAINT `fk_trips_input_by` FOREIGN KEY (`input_by`) REFERENCES `mova_users` (`id`) ON DELETE RESTRICT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
