-- MOVA Migration 007 — Fuel & Expense Reports
-- Depends on: trips (005), customers (003), vehicles (004), users (004)

CREATE TABLE IF NOT EXISTS `mova_fuel_reports` (
    `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    `customer_id` BIGINT UNSIGNED NOT NULL,
    `trip_id` BIGINT UNSIGNED NOT NULL,
    `vehicle_id` BIGINT UNSIGNED NOT NULL,
    `reported_by` BIGINT UNSIGNED NOT NULL,
    `fuel_date` DATE NOT NULL,
    `fuel_type` VARCHAR(20) NOT NULL COMMENT 'pertalite, pertamax, solar, dll',
    `liters` DECIMAL(8,2) NOT NULL,
    `price_per_liter` DECIMAL(10,2) NOT NULL,
    `total_cost` DECIMAL(12,2) NOT NULL COMMENT 'liters x price_per_liter',
    `km_at_refuel` INT NULL,
    `station_name` VARCHAR(100) NULL,
    `receipt_photo` VARCHAR(255) NULL,
    `status` ENUM('pending', 'approved', 'rejected') NOT NULL DEFAULT 'pending',
    `approved_by` BIGINT UNSIGNED NULL,
    `approved_at` TIMESTAMP NULL,
    `rejection_reason` TEXT NULL,
    `notes` TEXT NULL,
    `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (`id`),
    KEY `idx_customer_id` (`customer_id`),
    KEY `idx_trip_id` (`trip_id`),
    KEY `idx_vehicle_id` (`vehicle_id`),
    KEY `idx_status` (`status`),
    CONSTRAINT `fk_fr_customer` FOREIGN KEY (`customer_id`) REFERENCES `mova_customers` (`id`) ON DELETE CASCADE,
    CONSTRAINT `fk_fr_trip` FOREIGN KEY (`trip_id`) REFERENCES `mova_trips` (`id`) ON DELETE CASCADE,
    CONSTRAINT `fk_fr_vehicle` FOREIGN KEY (`vehicle_id`) REFERENCES `mova_vehicles` (`id`) ON DELETE RESTRICT,
    CONSTRAINT `fk_fr_reported_by` FOREIGN KEY (`reported_by`) REFERENCES `mova_users` (`id`) ON DELETE RESTRICT,
    CONSTRAINT `fk_fr_approved_by` FOREIGN KEY (`approved_by`) REFERENCES `mova_users` (`id`) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `mova_expense_reports` (
    `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    `customer_id` BIGINT UNSIGNED NOT NULL,
    `trip_id` BIGINT UNSIGNED NOT NULL,
    `vehicle_id` BIGINT UNSIGNED NOT NULL,
    `reported_by` BIGINT UNSIGNED NOT NULL,
    `expense_date` DATE NOT NULL,
    `category` VARCHAR(50) NOT NULL COMMENT 'tol, parkir, retribusi, penyeberangan, lainnya',
    `description` VARCHAR(200) NOT NULL,
    `amount` DECIMAL(12,2) NOT NULL,
    `receipt_photo` VARCHAR(255) NULL,
    `status` ENUM('pending', 'approved', 'rejected') NOT NULL DEFAULT 'pending',
    `approved_by` BIGINT UNSIGNED NULL,
    `approved_at` TIMESTAMP NULL,
    `rejection_reason` TEXT NULL,
    `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (`id`),
    KEY `idx_customer_id` (`customer_id`),
    KEY `idx_trip_id` (`trip_id`),
    KEY `idx_vehicle_id` (`vehicle_id`),
    KEY `idx_status` (`status`),
    CONSTRAINT `fk_er_customer` FOREIGN KEY (`customer_id`) REFERENCES `mova_customers` (`id`) ON DELETE CASCADE,
    CONSTRAINT `fk_er_trip` FOREIGN KEY (`trip_id`) REFERENCES `mova_trips` (`id`) ON DELETE CASCADE,
    CONSTRAINT `fk_er_vehicle` FOREIGN KEY (`vehicle_id`) REFERENCES `mova_vehicles` (`id`) ON DELETE RESTRICT,
    CONSTRAINT `fk_er_reported_by` FOREIGN KEY (`reported_by`) REFERENCES `mova_users` (`id`) ON DELETE RESTRICT,
    CONSTRAINT `fk_er_approved_by` FOREIGN KEY (`approved_by`) REFERENCES `mova_users` (`id`) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
